# Generated by Django 5.1.1 on 2024-11-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_nickname_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='record',
            field=models.TimeField(default="0:0:0"),
        ),
    ]
